alias e='source venv/bin/activate'
alias m='/usr/local/bin/python3.10 manage.py makemigrations'
alias mm='/usr/local/bin/python3.10 manage.py migrate'
alias b='/usr/bin/yarn --cwd l2-frontend/ build'
alias hgrep='history | grep'
alias clip='xclip -sel clip'
alias font-update='fc-cache -f -v'
